MA-21223-1 Remove KERNEL_OBJ/usr/include to fix 32bit compilation error
Remove unused include folder to fix following build error
met with IMX8_BUILD_32BIT_ROOTFS=true:

00:04:24 In file included from hardware/nxp/wlan/wifi_hal/cpp_bindings.cpp:22:
00:04:24 In file included from external/libnl/include/netlink/genl/genl.h:15:
00:04:24 In file included from external/libnl/include/netlink/netlink.h:19:
00:04:24 In file included from out/soong/.intermediates/bionic/libc/libc/android_vendor.33_arm_armv7-a-neon_cortex-a9_shared/gen/include/poll.h:38:
00:04:24 In file included from out/soong/.intermediates/bionic/libc/libc/android_vendor.33_arm_armv7-a-neon_cortex-a9_shared/gen/include/signal.h:35:
00:04:24 out/target/product/evk_8mq/obj/KERNEL_OBJ/usr/include/asm/sigcontext.h:77:2: error: unknown type name '__uint128_t'
00:04:24         __uint128_t vregs[32];
00:04:24         ^

Change-Id: Ia4e47f5cc64a38a7d2869bb714b45e5dc6406ce4
Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Reviewed-on: http://androidsource.nxp.com/project/21621
Reviewed-by: Xuegang Liu <xuegang.liu@nxp.com>
Reviewed-by: Yunjie Jia <yunjie.jia@nxp.com>